mode: single
max_exceeded: silent

blueprint:
  name: Marstek X range on the Meter TEST
  description: > 
    Control  Marstek Battery`s according to a grid sensor and a target range (v1.2)
    
    **Version**: 1.2
    e
    **Breaking change**: 'Minimum power setpoint' is inverted and renamed to 'Maximum Charge'

    Refactored min and max power setpoints, also new renamed.
    
    Structured and reordered the settings.
    
    set default interval and timeout time.

  
  author: Tazzios (Based on PimDoos`s works)
  domain: automation

  input:

    battery_section:
      name: Battery`s
      icon: mdi:battery
      input: 
        battery_device:
          name: Battery`s
          description: Marstek Battery devices to control
          selector:
            device:
              filter:
                integration: esphome
              multiple: true
        battery_soc_min:
          name: Minimum State of Charge
          description: Batteries below this level will not participate in the load balancing pool
          default: 0
          selector:
            number:
              min: 0
              max: 99

        battery_soc_max:
          name: Maximum State of Charge
          description: Batteries above this level will not participate in the load balancing pool
          default: 100
          selector:
            number:
              min: 1
              max: 100
        setpoint_optimal_value:
          name: Max optimal power
          description: Amount of power required before loadbalancing to more batteries
          default: 2000
          selector:
            number:
              min: 50
              max: 2500
        priority_offset_template:
          name: Priority offset template
          description: Template defining a value to rotate battery priority by. Values higher than the number of batteries will loop back to 0.
          default: "{{ now().day }}"
          selector:
            template:
        # This value represents the minimum(aka charging) total setpoint for all batteries combined.
        # It will be inverted later in the blueprint to calculate 'min_setpoint' for logic.    
        setpoint_min:
          name: Maximum Charge setpoint
          description:  If this is 0, charging is disabled. Total setpoint for all batteries combined.
          default: 12000
          selector:
            number:
              min: 0
              max: 12000
              mode: box

        setpoint_max:
          name: Maximum Discharge setpoint
          description: If this is 0, discharging is disabled. Total setpoint for all batteries combined.
          default: 12000
          selector:
            number:
              min: 0
              max: 12000
              mode: box  

    target_section:
      name: Target
      icon: mdi:target
      description: Set min and max the same if you want a fixed target.
      input:
        grid_entity:
          name: Grid
          description: Entity measuring grid net consumption
          selector:
            entity:
              filter:
                domain: sensor
                device_class: power
        offset_entity:
          name: Offset entities
          description: Entities whose value (in Watts) should be subtracted from the grid sensor. E.g. Car charger power sensor
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain:
                  - sensor
                  - number
                  - input_number


    setpoint_section:
      name: Setpoint
      icon: mdi:flash
      input: 
        setpoint_target_min:
            name: Target minimum value
            description: Lower limit for the Grid target band (in Watts)
            default: -200
            selector:
              number:
                min: -5000
                max: 5000
                mode: box

        setpoint_target_max:
          name: Target maximum value
          description: Upper limit for the Grid target band (in Watts)
          default: 200
          selector:
            number:
              min: -5000
              max: 5000
              mode: box           


    script_section:
      name: script
      icon: mdi:tune
      input:
        setpoint_smoothing_value:
          name: Smoothing value
          description: Maximum delta between two setpoints. This should not be lower than the Minimum Power of the battery.
          default: 2000
          selector:
            number:
              min: 50
              max: 2500
      
        update_interval:
          name: Update interval
          description: Time to wait before accepting new data from the grid sensor  
          default:
            hours: 0
            minutes: 0
            seconds: 10
          selector:
            duration: {}
    
        update_timeout:
          name: Update timeout
          description: Maximum time to wait for new data from the grid sensor 
          default:
            hours: 0
            minutes: 1
            seconds: 0
          selector:
            duration: {}


variables:
  device_ids: !input battery_device
  optimal_max_power: !input setpoint_optimal_value
  grid_entity: !input grid_entity
  smoothing: !input setpoint_smoothing_value
  #offset: !input setpoint_target_value
  
  target_min: !input setpoint_target_min
  target_max: !input setpoint_target_max

  
  
  offset_entity: !input offset_entity
  min_battery_level: !input battery_soc_min
  max_battery_level: !input battery_soc_max


  # This makes 'min_setpoint' the opposite (negative) of the configured minimum setpoint.
  # For example: if setpoint_min = 12000 → min_setpoint = -12000
  setpoint_min_value: !input setpoint_min
  min_setpoint: >
    {{ 0 - (setpoint_min_value | float) }}

  max_setpoint: !input setpoint_max

trigger:
  - trigger: state
    entity_id: !input grid_entity
  - trigger: homeassistant
    event: start

action:
  - variables:
      device_ids: >
        {% if device_ids is string %}{% set device_ids = [ device_ids ] %}{% endif %}
        {{ device_ids }}
      battery_count: >
        {{ device_ids | count }}
      priority_offset_template: !input priority_offset_template
      priority_offset: >
        {{ priority_offset_template % battery_count }}

  - variables:
      # Get Entity IDs from device IDs
      battery_rs485_control_entity: >
        {% set entities = namespace(rs485_control=[]) %}
        {% for device_id in device_ids %}
          {% set entities.rs485_control = entities.rs485_control + [device_entities(device_id) | list | select("search","_rs485_control_mode$") | list | join("")] %}
        {% endfor %}
        {{ entities.rs485_control[priority_offset:] + entities.rs485_control[:priority_offset] }}

      battery_mode_entity: >
        {% set entities = namespace(mode=[]) %}
        {% for device_id in device_ids %}
          {% set entities.mode = entities.mode + [device_entities(device_id) | list | select("search","_forcible_charge_discharge$") | list | join("")] %}
        {% endfor %}
        {{ entities.mode[priority_offset:] + entities.mode[:priority_offset] }}
        
      battery_acpower_entity: >
        {% set entities = namespace(acpower=[]) %}
        {% for device_id in device_ids %}
        {% set entities.acpower = entities.acpower + [device_entities(device_id) | list | select("search","_ac_power$") | list | join("")] %}
        {% endfor %}
        {{ entities.acpower[priority_offset:] + entities.acpower[:priority_offset] }}

      battery_setpointcharge_entity: >
        {% set entities = namespace(setpointcharge=[]) %}
        {% for device_id in device_ids %}
          {% set entities.setpointcharge = entities.setpointcharge + [device_entities(device_id) | list | select("search","_forcible_charge_power$") | list | join("")] %}
        {% endfor %}
        {{ entities.setpointcharge[priority_offset:] + entities.setpointcharge[:priority_offset] }}

      battery_setpointdischarge_entity: >
        {% set entities = namespace(setpointdischarge=[]) %}
        {% for device_id in device_ids %}
          {% set entities.setpointdischarge = entities.setpointdischarge + [device_entities(device_id) | list | select("search","_forcible_discharge_power$") | list | join("")] %}
        {% endfor %}
        {{ entities.setpointdischarge[priority_offset:] + entities.setpointdischarge[:priority_offset] }}

      # Get grid power and convert to Watts
      grid: >
        {% set grid_unit = state_attr(grid_entity, "unit_of_measurement") %}
        {% set multiplier = 1 if grid_unit == "W" else 1000 if grid_unit == "kW" else 1 %}
        {% set grid_power = states(grid_entity) | float %}
        {{ grid_power * multiplier }}

  - variables:
      battery: >
        {{  battery_acpower_entity | map("states") | list | map('int') | sum }}
      offset_total: >
        {% if offset_entity is string %}{% set offset_entity = [offset_entity] %}{% endif %}
        {{ offset_entity | map("states") | map("int") | sum }}

      setpoint: >
        {% set net_load = battery + grid %}
        {% if net_load < target_min %}
          {# te veel export -> laad batterij #}
          {% set target_diff = (net_load - offset_total ) - target_min %}
        {% elif net_load > target_max %}
          {# te veel import -> ontlaad batterij #}
          {% set target_diff = (net_load - offset_total) - target_max %}
        {% else %}
          {% set target_diff = 0 - offset_total%}
        {% endif %}

        {% if target_diff != 0%}
            {% set lower = [target_diff, battery - smoothing, min_setpoint] | max %}
            {% set setpoint_smooth = [lower, battery + smoothing, max_setpoint] | min %}
            {{ setpoint_smooth }}
        {% else %}
            {{ target_diff }}
        {% endif %}

  - variables:      
      battery_setpoints: >
        {% set num_optimal = ((setpoint | abs) / optimal_max_power) | round(0,'ceil') %}
        {% set batteries = namespace(entities=[], available=[], standby=[]) %}
        {% for i in range(0,battery_count) %}
          {# Haal de SOC entity direct op voor deze device #}
          {% set soc_entity = device_entities(device_ids[i]) | list | select("search","_state_of_charge$") | list | first %}
          {% set soc_value = states(soc_entity) | default(0) | int %}
        
          {% if batteries.available | count < num_optimal 
             and states(battery_rs485_control_entity[i]) == "enable"
             and (soc_value >= min_battery_level or setpoint < 0)
             and (soc_value <= max_battery_level or setpoint > 0) %}  
            {% set batteries.available = batteries.available + [i] %}
          {% else %}
            {% set batteries.standby = batteries.standby + [i] %}
          {% endif %}									 		 
        {% endfor %}
        {% set divisor = (batteries.available | count) if (batteries.available | count) > 0 else 1 %}
        {% for i in batteries.available %}
          {% set value = (setpoint / divisor) | int %}
          {% set value = [[value, -2200] | max, 2200] | min %}
          {% set batteries.entities = batteries.entities + [{
            "setpointcharge": battery_setpointcharge_entity[i],
            "setpointdischarge": battery_setpointdischarge_entity[i],
            "rs485_control": battery_rs485_control_entity[i],
            "mode": battery_mode_entity[i],
            "value": value
          }] %}
        {% endfor %}
        {% for i in batteries.standby %}
          {% set batteries.entities = batteries.entities + [{
            "setpointcharge": battery_setpointcharge_entity[i],
            "setpointdischarge": battery_setpointdischarge_entity[i],
            "rs485_control": battery_rs485_control_entity[i],
            "mode": battery_mode_entity[i],
            "value": 0
          }] %}
        {% endfor %}
        {{ batteries.entities }}

  # --- Nul setpoints (standby / idle) ---
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ battery_setpoints | selectattr('value','eq',0) | list | count > 0 }}
        sequence:
          - repeat:
              for_each: >
                {{ battery_setpoints | selectattr('value','eq',0) | list }}
              sequence:
                - condition: template
                  value_template: >
                    {{ states(repeat.item.rs485_control) == "enable" }}
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ states(repeat.item.mode) != "stop" }}
                      sequence:
                        - action: select.select_option
                          target:
                            entity_id: >
                              {{ repeat.item.mode }}
                          data:
                            option: stop
                        - action: number.set_value
                          continue_on_error: true
                          target:
                            entity_id: >
                              {{ repeat.item.setpointcharge }}
                          data:
                            value: 0
                        - action: number.set_value
                          continue_on_error: true
                          target:
                            entity_id: >
                              {{ repeat.item.setpointdischarge }}
                          data:
                            value: 0

  # --- Negatieve setpoints (laden) ---
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ battery_setpoints | selectattr('value','lt',0) | list | count > 0 }}
        sequence:
          - repeat:
              for_each: >
                {{ battery_setpoints | selectattr('value','lt',0) | list }}
              sequence:
                - condition: template
                  value_template: >
                    {{ states(repeat.item.rs485_control) == "enable" }}
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ states(repeat.item.mode) != "charge" }}
                      sequence:
                        - action: select.select_option
                          target:
                            entity_id: >
                              {{ repeat.item.mode }}
                          data:
                            option: charge
                - action: number.set_value
                  continue_on_error: true
                  target:
                    entity_id: >
                      {{ repeat.item.setpointcharge }}
                  data:
                    # negatief setpoint omzetten in positief
                    value: >
                      {{ repeat.item.value | abs | int }}
                - action: number.set_value
                  continue_on_error: true
                  target:
                    entity_id: >
                      {{ repeat.item.setpointdischarge }}
                  data:
                    # ander setpoint wissen
                    value: 0

  # --- Positieve setpoints (ontladen) ---
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ battery_setpoints | selectattr('value','gt',0) | list | count > 0 }}
        sequence:
          - repeat:
              for_each: >
                {{ battery_setpoints | selectattr('value','gt',0) | list }}
              sequence:
                - condition: template
                  value_template: >
                    {{ states(repeat.item.rs485_control) == "enable" }}
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {{ states(repeat.item.mode) != "discharge" }}
                      sequence:
                        - action: select.select_option
                          target:
                            entity_id: >
                              {{ repeat.item.mode }}
                          data:
                            option: discharge
                - action: number.set_value
                  continue_on_error: true
                  target:
                    entity_id: >
                      {{ repeat.item.setpointdischarge }}
                  data:
                    value: >
                      {{ repeat.item.value | int }}
                - action: number.set_value
                  continue_on_error: true
                  target:
                    entity_id: >
                      {{ repeat.item.setpointcharge }}
                  data:
                    value: 0

                      

  - delay: !input update_interval
